In [20]:
import pandas as pd
import numpy as np

data = pd.read_csv('DTP_data_final_fix1.csv', index_col=0)
data

,Unnamed: 0,title,r_i_docking_score,SMILES
100774,101135,517865,-13.41990,O=C(c1ccc(C(=O)c2ccc(O)cc2O)cc1)c1ccc(O)cc1O
4682,4713,8662,-13.19900,Oc1cc2c(cc1O)[C@@H]1c3ccc(O)c(O)c3OC[C@]1(O)C2
6380,6423,11870,-13.10250,O=C1OC[C@H]2[C@H](c3ccc(O)c(O)c3)c3cc(O)c(O)cc...
120462,120925,694230,-12.84750,O=C(NC(=S)NC(=O)c1cc(O)c(O)c(O)c1)c1cc(O)c(O)c...
124587,125070,721171,-12.51900,OC[C@H]1O[C@@H](Oc2cc(/C=C/c3ccc(O)cc3)ccc2O)[...
...,...,...,...,...
53251,53441,133656,4.67344,C[N+]1(C)BC[N+](C)(C)BC1
53252,53442,133661,4.85748,C[N+]1(C)[BH2-]C[N+](C)(C)[B@H-]([n+]2ccccc2)C1
8342,8392,16612,5.59103,COc1cc2c(c(NC(C)=O)c1)N(C(C)=O)CCC2
113228,113650,657650,6.47326,CC1=C(C(=O)N(C(C)C)C(C)C)CC(C(=O)N(C(C)C)C(C)C...
20274,20351,43359,6.77941,CCC(=O)Oc1cccc(C(OC(=O)CC)OC(=O)CC)c1

In [21]:
data = data.rename(columns={'title': 'NSC', 'r_i_docking_score': 'docking_score'})
data

,Unnamed: 0,NSC,docking_score,SMILES
100774,101135,517865,-13.41990,O=C(c1ccc(C(=O)c2ccc(O)cc2O)cc1)c1ccc(O)cc1O
4682,4713,8662,-13.19900,Oc1cc2c(cc1O)[C@@H]1c3ccc(O)c(O)c3OC[C@]1(O)C2
6380,6423,11870,-13.10250,O=C1OC[C@H]2[C@H](c3ccc(O)c(O)c3)c3cc(O)c(O)cc...
120462,120925,694230,-12.84750,O=C(NC(=S)NC(=O)c1cc(O)c(O)c(O)c1)c1cc(O)c(O)c...
124587,125070,721171,-12.51900,OC[C@H]1O[C@@H](Oc2cc(/C=C/c3ccc(O)cc3)ccc2O)[...
...,...,...,...,...
53251,53441,133656,4.67344,C[N+]1(C)BC[N+](C)(C)BC1
53252,53442,133661,4.85748,C[N+]1(C)[BH2-]C[N+](C)(C)[B@H-]([n+]2ccccc2)C1
8342,8392,16612,5.59103,COc1cc2c(c(NC(C)=O)c1)N(C(C)=O)CCC2
113228,113650,657650,6.47326,CC1=C(C(=O)N(C(C)C)C(C)C)CC(C(=O)N(C(C)C)C(C)C...
20274,20351,43359,6.77941,CCC(=O)Oc1cccc(C(OC(=O)CC)OC(=O)CC)c1

In [22]:
docking_scores = {
    517865: -5.22,
    43359: -30.21,
    19139: -0.21,
    16612: -6.82,
    69356: -55.12,
    109327: -7.21,
    120688: -0.51,
    303769: -42.12,
    320852: -72.53,
    133656: -0.12,
}

data['docking_score'] = data['NSC'].map(docking_scores)
data

,Unnamed: 0,NSC,docking_score,SMILES
100774,101135,517865,-5.22,O=C(c1ccc(C(=O)c2ccc(O)cc2O)cc1)c1ccc(O)cc1O
4682,4713,8662,NaN,Oc1cc2c(cc1O)[C@@H]1c3ccc(O)c(O)c3OC[C@]1(O)C2
6380,6423,11870,NaN,O=C1OC[C@H]2[C@H](c3ccc(O)c(O)c3)c3cc(O)c(O)cc...
120462,120925,694230,NaN,O=C(NC(=S)NC(=O)c1cc(O)c(O)c(O)c1)c1cc(O)c(O)c...
124587,125070,721171,NaN,OC[C@H]1O[C@@H](Oc2cc(/C=C/c3ccc(O)cc3)ccc2O)[...
...,...,...,...,...
53251,53441,133656,-0.12,C[N+]1(C)BC[N+](C)(C)BC1
53252,53442,133661,NaN,C[N+]1(C)[BH2-]C[N+](C)(C)[B@H-]([n+]2ccccc2)C1
8342,8392,16612,-6.82,COc1cc2c(c(NC(C)=O)c1)N(C(C)=O)CCC2
113228,113650,657650,NaN,CC1=C(C(=O)N(C(C)C)C(C)C)CC(C(=O)N(C(C)C)C(C)C...
20274,20351,43359,-30.21,CCC(=O)Oc1cccc(C(OC(=O)CC)OC(=O)CC)c1

In [26]:
NSC_list = list(docking_scores.keys())
NSC_indexes = data['NSC'].isin(NSC_list)
data_with_score = data[NSC_indexes]
data_with_score

,Unnamed: 0,NSC,docking_score,SMILES
100774,101135,517865,-5.22,O=C(c1ccc(C(=O)c2ccc(O)cc2O)cc1)c1ccc(O)cc1O
30163,30273,69356,-55.12,Cc1ccnc(N2C(=O)c3ccccc3[C@]2(O)c2ccccc2)c1
9464,9518,19139,-0.21,Cn1ncc2c(NCCc3ccccc3)nc(Cl)nc21
44958,45126,109327,-7.21,COc1ccc2nc3ccccc3c(NCCC[NH+](C)C)c2c1
84363,84655,303769,-42.12,CC1=[NH+]N(C(=O)c2ccncc2)C(=O)[C@@H]1/N=N/c1cc...
48783,48961,120688,-0.51,O=C([O-])c1ccc(/C=[NH+]/[NH+]=C2c3ccccc3-c3ccc...
86381,86686,320852,-72.53,N/[NH+]=C1\C(OC(=O)Nc2cccc(Cl)c2)=Nc2ccccc21
53251,53441,133656,-0.12,C[N+]1(C)BC[N+](C)(C)BC1
8342,8392,16612,-6.82,COc1cc2c(c(NC(C)=O)c1)N(C(C)=O)CCC2
20274,20351,43359,-30.21,CCC(=O)Oc1cccc(C(OC(=O)CC)OC(=O)CC)c1

In [32]:
# Make dataset smaller for developing purposes

data_len = 200

if len(data_with_score) >= data_len:
    short_data = data_with_score.head(data_len)
else:
    remaining_rows = data_len - len(data_with_score)
    data_without_score = data[data['docking_score'].isna()].head(remaining_rows)
    short_data = pd.concat([data_with_score, data_without_score])

short_data = short_data.sort_values(by=['NSC'])
short_data

,Unnamed: 0,NSC,docking_score,SMILES
1566,1576,2819,NaN,Oc1cc(O)c2c(c1)O[C@H](c1ccc(O)c(O)c1)[C@@H](O)C2
2337,2349,4288,NaN,CC(=O)Nc1ccc(C(O)c2ccc(NC(C)=O)cc2)cc1
3986,4007,7333,NaN,O=C1C=C2C[C@@]3(O)COc4c(ccc(O)c4O)C3=C2C=C1O
4681,4712,8661,NaN,Oc1ccc2c(c1)OC[C@@]1(O)Cc3cc(O)c(O)cc3[C@H]21
4682,4713,8662,NaN,Oc1cc2c(cc1O)[C@@H]1c3ccc(O)c(O)c3OC[C@]1(O)C2
...,...,...,...,...
131071,131568,767424,NaN,Cn1cc(C2=C(c3cccc(OC[C@H](O)CO)c3)C(=O)NC2=O)c...
131097,131594,767702,NaN,CCc1c(C)c2ccc(O)c(N3C(=O)C(=O)N(c4ccccc4)C3=O)...
131222,131719,768448,NaN,O[Si](O)(c1ccc(F)c2ccccc12)c1ccc(F)c2ccccc12
131597,132094,774658,NaN,C[NH+](C)CCCN(Cc1ccccc1O)C(=S)Nc1cccc2ccccc12
131940,132437,780187,NaN,Cc1cccc(-n2c(C)nc3ccc(NC(=O)NCCCl)cc3c2=O)c1

In [33]:
#data.to_csv('DTP_data_labels_dummy.csv')
short_data.to_csv('DTP_data_labels_dummy_short.csv')